name: Context Example

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "Step-1"
              env:  
                MY_ACTION: ${{github.action}}
                MY_ACTOR: ${{github.action_status}}
                MY_REPO: ${{github.action_repository}}
                API_KEY: ${{secrets.API_KEY}}
              run: |
                echo "Hello! $MY_ACTOR" 
                echo "Hello! $MY_REPO"
                echo "Hello! $API_KEY"
             
