name: Context Example

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "Step-1"
              env: 
                MY_ACTION: ${{github.action}}
                MY_ACTOR: ${{github.actor}}
                MY_REF: ${{github.action_ref}}
              run: |
                echo "Hello! $MY_ACTOR" \n
                echo "Hello! $MY_REF"
             
