name: Context Example

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "Step-1"
              env: 
                MY_ACTION: ${{github.action}}
                MY_ACTOR: ${{github.action_status}}
                MY_REPO: ${{github.action_repository}}
              run: |
                echo "Hello! $MY_ACTOR" \n
                echo "Hello! $MY_REPO"
             
