name: Webhook Event example
on:
  repository_dispatch:
    types:
      - webhook
      
jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: 'echo "Event of type: $GITHUB.EVENT.ACTION"'